num1 = int(input("Introduce el primer número: "))
num2 = int(input("Introduce el segundo número: "))
print("La suma es: " ,(num1 + num2))
print("La resta es: " ,(num1 - num2))
print("La multiplicación es: " ,(num1 * num2))
print("La división es: " ,(num1 / num2))
print("La division euclidea es: " ,(num1 // num2))
